behav_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('behav_tracker_app.urls'))
]

behav_tracker_app/urls.py
from django.urls import path
from . import views

app_name = 'behavtrackerapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('viewstudents/', views.students, name='viewstudents'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('teachers/', views.get_teachers, name='get_teachers'),
    path('student/<str:student_id>/', views.get_student, name='get_student'),
    path('viewStudents/', views.view_students, name='viewStudents'),
    path('save_behav/<str:student_id>', views.save_behav, name="save_behav"),
    path('studentinfo/<str:student_id>', views.get_behaviors, name="student_info"),
    path('student_behaviors/<str:student_id>', views.student_behaviors, name='behaviors'),
    path('signup/', views.signup, name='signup'),
    path('newstudent/', views.new_student, name='newstudent'),
    
]

behav_tracker_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Behavior(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    antecedent = models.CharField(max_length=50)
    behavior = models.CharField(max_length=50)
    intervention = models.CharField(max_length=50)
    location = models.CharField(max_length=50)

    def __str__(self):
        return self.behavior

class Class(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=20)
    grade = models.CharField(max_length=3)
    behavior = models.ManyToManyField(Behavior, related_name='students', blank=True,)
    classes = models.ManyToManyField(Class, related_name='students', blank=True)

    def __str__ (self):
        return self.name

class Teacher(AbstractUser):
    name = models.CharField(max_length=20)
    classes = models.ManyToManyField(Class, related_name='teacher', blank=True)
    student = models.ManyToManyField(Student, related_name='teacher', blank=True)
    admin = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    

behav_tracker_app/views.py
import json
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Teacher, Class, Student, Behavior
from django.contrib import auth
from django.core import serializers

def index(request):
    return render(request, 'behav_tracker_app/index.html')

def students(request):
    return render(request, 'behav_tracker_app/viewstudents.html')

def student_behaviors(request, student_id):
    context = {'student_id': student_id}
    return render(request, 'behav_tracker_app/studentinfo.html', context)

def signup(request):
    if request.method == 'POST':
        Teacher.objects.create_user(
            username=request.POST['username'],
            password=request.POST['password'],
            name=request.POST['name']
        )
        return redirect('behavtrackerapp:login')
    return render(request, 'behav_tracker_app/newteacher.html')

def new_student(request):
    if request.method == 'POST':
        form = request.POST
        newStudent = Student()
        newStudent.name = form.get('name')
        newStudent.grade = form.get('grade')
        newStudent.save()
        teacher_id = form.get('selectedTeacher')
        teacher = Teacher.objects.get(name=teacher_id)
        print(teacher)
        teacher.student.add(newStudent)

        return redirect('behavtrackerapp:index')
    return render(request, 'behav_tracker_app/newstudent.html')

def get_teachers(request):
    teachers_query = Teacher.objects.filter(username=request.user.username)
    print(teachers_query)
    teachers = []
    for teacher in teachers_query:
        teachers.append({
            'name': teacher.name,
            'classes': list(teacher.classes.filter().values('name')),
            'students': list(teacher.student.filter().values('name', 'id'))
        })

    return JsonResponse(teachers, safe=False)

def get_student(request, student_id):
    student = Student.objects.get(id=student_id)
    behaviors = list(student.behavior.filter().values('antecedent', 'behavior', 'created_date', 'location', 'intervention'))
    
    return JsonResponse({'data': behaviors})

def save_behav(request, student_id):
    student = Student.objects.get(id=student_id)

    if request.method == 'POST':
        form = request.POST
        newBehav = Behavior()
        newBehav.antecedent = form.get('antecedent')
        newBehav.behavior = form.get('behavior')
        newBehav.intervention = form.get('intervention')
        newBehav.location = form.get('location')
        newBehav.save()
        student.behavior.add(newBehav)
        student.save()

    return redirect('behavtrackerapp:index')

def view_students(request):
    teacher = Teacher.objects.get(username=request.user.username)
    student_query = teacher.student.all()
    
    students = []
    for student in student_query:
        students.append({
           'name': student.name
        })

    return JsonResponse(students, safe=False)

def get_behaviors(request, student_id):
    student = Student.objects.get(name=student_id)
    behaviors = list(student.behavior.filter().values('antecedent', 'behavior', 'created_date', 'location', 'intervention'))
    
    return JsonResponse(behaviors, safe=False)

def login(request):
    if request.method == "GET":
        return render(request, "behav_tracker_app/login.html")
    elif request.method == "POST":
        data = json.loads(request.body)
        username = data.get("username", "")
        password = data.get("password", "")

        user = auth.authenticate(request, username=username, password=password)
        if user == None:
            return JsonResponse({"message": "Invalid username or password."})
        else:
            auth.login(request, user)
            return JsonResponse({"message": "ok"})

def logout(request):
    auth.logout(request)
    return redirect('behavtrackerapp:login')

behav_tracker_app/templates/behav_tracker_app/_footer.html
<footer class="page-footer blue-grey lighten-1">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">About Us</h5>
          <p class="grey-text text-lighten-4">Built as a Capstone for a web developement course through PDX Code Guild! Check out their link on the left. For more information about the app or to contact my creator please contact Wesley Anding!</p>
        </div>
        <div class='col l6 s12'>
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://pdxcodeguild.com/">PDX Code Guild</a></li>
            <li><a class="white-text" href="https://wesleyanding.github.io/"></a>Wesley Anding - my creator!</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>

behav_tracker_app/templates/behav_tracker_app/_navbar.html
{% load static %}
<header>
    <nav class="blue-grey lighten-1" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="{% url 'behavtrackerapp:index' %}" class="brand-logo">
                <img src="{% static 'behav_tracker_app/pics/BTlogo.png' %}" alt="Behavior Tracker logo">
            </a>
            <ul class="right hide-on-med-and-down">
                {% if not request.user.is_anonymous %}
                <li><a href="{% url 'behavtrackerapp:newstudent' %}">Add a Student</a></li>
                <li><a href="{% url 'behavtrackerapp:viewstudents' %}" >View Students</a></li>
                <li><a href="{% url 'behavtrackerapp:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'behavtrackerapp:login' %}">Login</a></li>
                <li><a href="{% url 'behavtrackerapp:signup' %}">Sign up</a></li>
                {% endif %}
            </ul>
            <ul id="nav-mobile" class="sidenav">
                {% if not request.user.is_anonymous %}
                <li><a href="{% url 'behavtrackerapp:logout' %}">Logout</a></li>
                <li><a href="{% url 'behavtrackerapp:newstudent' %}">Add a Student</a></li>
                <li><a href="{% url 'behavtrackerapp:viewstudents' %}" >View Students</a></li>  
                {% else %} 
                <li><a href="{% url 'behavtrackerapp:login' %}">Login</a></li>
                <li><a href="{% url 'behavtrackerapp:signup' %}">Sign up</a></li>
                {% endif %}
            </ul>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>
    </nav>
</header>

behav_tracker_app/templates/behav_tracker_app/_styles.html
   {% load static %}
    <script defer src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script defer src="{% static 'behav_tracker_app/js/materialize.js' %}"></script>
    <script defer src="{% static 'behav_tracker_app/js/init.js' %}"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'behav_tracker_app/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'behav_tracker_app/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>

behav_tracker_app/templates/behav_tracker_app/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Behavior Tracker</title>
    <script src="https://unpkg.com/vue@3"></script>
    {% include 'behav_tracker_app/_styles.html' %}
    <script defer src="{% static 'behav_tracker_app/app.js' %}"></script>
    
    <style>
        {box-sizing: border-box}

        .form-popup {
            display: none;
            position: fixed;
            bottom: 0;
            right: 15px;
            border: 3px solid #f1f1f1;
            z-index: 9;
        }
        .form-container {
            max-width: 300px;
            padding: 10px;
            background-color: white;
        }
        
    </style>
</head>
<body>
    {% include 'behav_tracker_app/_navbar.html' %}
    <main>
        {% if not request.user.is_anonymous %}
        <div id="app">
            <div class='container'>
                <h4 class='header center blue-grey-text lighten-1-text'>Select a student to add a behavior</h4>
                <div v-for='teacher in teachers' v-bind:value='teacher.id' class='col s4 offset-s4 blue-grey-text lighten-1-text'>
                    <h5 class='header col s4 offset-s4 light'>[[teacher.name]]</h5>
                    <div>
                        <select v-model='selectedStudent' v-on:change='fetchStudents()' class="browser-default">
                            <option selected disabled >Select a student</option>
                            <option v-for='student in teacher.students' v-bind:value='student.id'>
                                [[student.name]]
                            </option>
                        </select>    
                    </div>
                    <div class='divider'></div>
    
                    <div class='form-popup' id='myForm' class='container'>
        
                        <form v-bind:action="'save_behav/'+ selectedStudent" class='form-container' method='POST'>
                            {% csrf_token %}
                            
                            <div class='input-field col s6'>
                                <label for="antecedent"><b>Antecedent</b></label>
                                <input type="text" placeholder='Enter Antecedent' name='antecedent'>
                            </div>
                            <div class='input-field col s6'>
                                <label for="behavior"><b>Behavior</b></label>
                                <input type="text" placeholder='Enter Behavior' name="behavior"> 
                            </div>
                            <div class='input-field col s6'>
                                <label for="intervention"><b>Intervention</b></label>
                                <input type="text" placeholder='Enter Intervention' name='intervention'>
                            </div>
                            <div class='input-field col s6'>
                                <label for="location"><b>Location</b></label>
                                <input type="text" placeholder='Enter Location' name='location'>
                            </div>
                            
                            <button type='submit' class='btn-small blue-grey lighten-1'>Submit</button>
                            <button type='button' class='btn-small cancel blue-grey lighten-1' v-on:click='closeForm()'>Close</button>
                            
                        </form>
                    </div> 
                </div>
            </div>
        </div>
        {% else %}
        <div class="section no-pad-bot" id="index-banner">
            <div class="container">
              <br><br>
              <h1 class="header center blue-grey-text lighten-1-text">Behavior Tracker</h1>
              <div class="row center">
                <h5 class="header col s12 light">We aim to ease and consolidate the process of recording and documenting trouble behaviors with students. Our uncomplicated form and quick process of documenting issues into an easy to read table will facilitate meetings with both parents and administration. </h5>
              </div>
              <div class="row center">
                <a href="{% url 'behavtrackerapp:signup' %}" id="download-button" class="btn-large waves-effect waves-light blue-grey lighten-1 ">Sign up!</a>
              </div>
              <br><br>
            </div>
          </div>        {% endif %}
        <br>
    </main>
    {% include 'behav_tracker_app/_footer.html' %}
</body>
</html>

behav_tracker_app/templates/behav_tracker_app/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/3.0.1/js.cookie.min.js" integrity="sha512-wT7uPE7tOP6w4o28u1DN775jYjHQApdBnib5Pho4RB0Pgd9y7eSkAV1BTqQydupYDB9GBhTcQQzyNMPMV3cAew==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script defer src="{% static 'behav_tracker_app/login.js' %}"></script>
  {% include 'behav_tracker_app/_styles.html' %}
</head>
<body>
  {% include 'behav_tracker_app/_navbar.html' %}
  <div class='row'>
    <h1 class='center blue-grey-text lighten-1-text'>Login</h1>
    <form id="login-form" class='col s8 offset-s2'>
      <input id="username" type="text" placeholder="Username:" required>
      <input id="password" type="password" placeholder="Password:" required>
      <button class='btn blue-grey lighten-1'>Login</button>
    </form>
  </div>
</body>
</html>

behav_tracker_app/templates/behav_tracker_app/newstudent.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Behavior Tracker</title>
    <script src="https://unpkg.com/vue@3"></script>
    {% include 'behav_tracker_app/_styles.html' %}
    <script defer src="{% static 'behav_tracker_app/app.js' %}"></script>

</head>
<body>
    {% include 'behav_tracker_app/_navbar.html' %}
    <div class='row'>
        <h3 class='center blue-grey-text lighten-1-text'>Add new student</h3>
        <div id='app'>
            <form action="{% url 'behavtrackerapp:newstudent' %}" method='POST' class='col s8 offset-s2'>
                {% csrf_token %}
                <input type="text" name='name' placeholder='name'>
                <input type="text" name='grade' placeholder='grade'>
                <div class='input-field'>
                    <select v-model='created' name='selectedTeacher' class='browser-default'>
                        <option selected disabled >Select a Teacher</option>
                        <option v-for='teacher in teachers' v-bind:value='teacher.id'>
                            [[teacher.name]]
                        </option>
                    </select>
                </div>
                <button class='btn blue-grey lighten-1'>Create Student</button>
            </form>
        </div>
    </div>
    {% include 'behav_tracker_app/_footer.html' %}
</body>
</html>

behav_tracker_app/templates/behav_tracker_app/newteacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Behavior Tracker</title>
    {% include 'behav_tracker_app/_styles.html' %}

</head>
<body>
    {% include 'behav_tracker_app/_navbar.html' %}
    <div class='row'>
        <h3 class='center blue-grey-text lighten-1-text'>Add a Teacher</h3>
        <form action="{% url 'behavtrackerapp:signup' %}" method="POST" class='col s4 offset-s4'>
            {% csrf_token %}
            <input type="text" name='username' placeholder='Username'>
            <input type="password" name='password' placeholder='Password'>
            <input type="text" name='name' placeholder="Teacher's name">
            <button class='btn blue-grey lighten-1'>Sign up</button>
        </form>
    </div>
    {% include 'behav_tracker_app/_footer.html' %}
</body>
</html>

behav_tracker_app/templates/behav_tracker_app/studentinfo.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Behavior Tracker</title>
    <script src="https://unpkg.com/vue@3"></script>
    {% include 'behav_tracker_app/_styles.html' %}
    <script defer src="{% static 'behav_tracker_app/app.js' %}"></script>
</head>
<body>
    {% include 'behav_tracker_app/_navbar.html' %}
    <main>
        <input type="hidden" value='{{student_id}}' id='student_id'>
        <div id="app" class='section no-pad-bot'>
            <div class='container'>
                <table class='highlight responsive-table blue-grey-text lighten-1-text'>
                    <tr>
                        <th>Antecedent</th>
                        <th>Behavior</th>
                        <th>Created Date</th>
                        <th>Location</th>
                        <th>Intervention</th>
                    </tr>
                    <tr v-for='behavior in behaviors'>
                        <td>[[behavior.antecedent]]</td>
                        <td>[[behavior.behavior]]</td>
                        <td>[[behavior.created_date]]</td>
                        <td>[[behavior.location]]</td>
                        <td>[[behavior.intervention]]</td>
                    </tr>
                </table>
            </div>
        </div>
    </main>
    {% include 'behav_tracker_app/_footer.html' %}
</body>
</html>

behav_tracker_app/templates/behav_tracker_app/viewstudents.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Behavior Tracker</title>
    <script src="https://unpkg.com/vue@3"></script>
    {% include 'behav_tracker_app/_styles.html' %}
    <script defer src="{% static 'behav_tracker_app/app.js' %}"></script>

</head>
<body>
    {% include 'behav_tracker_app/_navbar.html' %}
    <main>
        <div id='app' class='container'>
            <div v-for='student in students' v-bind:value='student.id' class='center'>
                <div class="row center">
                    <div class=" center s12 offset-2 m6">
                        <div class="card small">
                            <div class="card-image">
                                <a v-bind:href="'../student_behaviors/'+ student.name" class='blue-grey-text lighten-1-text'>[[student.name]]</a>
                            </div>        
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% include 'behav_tracker_app/_footer.html' %}
</body>
</html>